using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RedCarpet
{
    class LevelDatabase
    {
        public static string GetLevelName(string LevelFileName)
        {
            Dictionary<string, string> Database = new Dictionary<string, string>
        {
            {"1-1 Super Bell Hill - Section 1", "EnterCatMarioStageMap1.szs" },
            {"1-2 Koopa Troopa Cave - Section 1", "NokonokoCaveStageMap1.szs"},
            {"1-2 Koopa Troopa Cave - Bonus Room", "GoldRoomKouraZoneMap1.szs"},
            {"1-3 Mount Beanpole - Section 1", "ClimbMountainStageMap1.szs"},
            {"1-3 Mount Beanpole - Sky Section", "CloudBonusEZoneMap1.szs" },
            {"1-3 Mount Beanpole - Bonus Room", "AoCoinFirstZoneMap1.szs" },
            {"1-4 Plessies Plunging Falls - Section 1", "DownRiverStageMap1.szs" },
            {"1-5 Switch Scramble Circus - Section 1", "FlipCircusStageMap1.szs"},
            {"1-5 Switch Scramble Circus - Bonus Room", "FlipCircusBonusRoomZoneMap1.szs" },
            {"1-A Chargin Chuck Blockade - Section 1", "GateKeeperBullLv1StageMap1.szs"},
            {"1-Castle Bowsers Highway Showdown - Section 1", "KoopaChaseLv1StageMap1.szs"},
            {"1-Castle Bowsers Highway Showdown Fairy Cutscene Section", "DemoWorldClear01StageMap1.szs"},
            {"1-Toad Captain Toad Goes Forth", "KinopioBrigadeTentenStageMap1.szs"},
            {"2-1 Conkdor Canyon - Section 1", "SideWaveDesertStageMap1.szs"},
            {"2-1 Conkdor Canyon - Bonus Room", "GoldRoomWaterfallZoneMap1.szs" },
            {"2-2 Puffprod Peaks - Section 1", "TouchAndMikeStageMap1.szs"},
            {"2-2 Puffprod Peaks - Section 2", "TouchAndMikeSecondZoneMap1.szs"},
            {"2-2 Puffprod Peaks - Bonus Room", "TouchAndMikeBonusRoomZoneMap1.szs"},
            {"2-2 Puffroad Peaks - Sky Section", "CloudBonusTouchAndMikeZoneMap1.szs"},
            {"2-3 Shadow-Play Alley - Section 1", "ShadowTunnelStageMap1.szs"},
            {"2-4 Really Rolling Hills - Section 1", "RotateFieldStageMap1.szs"},
            {"2-4 Really Rolling Hills - Section 2", "RotateFieldBZoneMap1.szs"},
            {"2-4 Really Rolling Hills - Section 3", "RotateFieldGoalZoneMap1.szs"},
            {"2-4 Really Rolling Hills - Bonus Room", "RotateFieldDoremiZoneMap1.szs"},
            {"2-5 Double Cherry Pass - Section 1", "DoubleMarioFieldStageMap1.szs" },
            {"2-A Big Galoomba Blockade - Section 1", "GateKeeperKuribonLv1StageMap1.szs"},
            {"2-Castle Bowsers Bullet Bill Brigade Fairy Cutscene Section", "DemoWorldClear02StageMap1.szs"},
            {"2-Mystery House Melee - Basic Room", "MysteryHouseEnemyZoneMap1.szs"},
            {"2-Mystery House Melee - Section 1", "MysteryHouseEnemyStageMap1.szs"},
            {"2-Tank Bowsers Bullet Bill Brigade - Section 1", "KillerTankStageMap1.szs"},
            {"2-Tank Bowsers Bullet Bill Brigade - Section 2", "TankBunbun01ZoneMap1.szs"},
            {"3-1 Snowball Park - Section 1", "SnowBallParkStageMap1.szs"},
            {"3-2 Chain-Link Charge - Section 1", "ClimbWirenetStageMap1.szs"},
            {"3-3 Shifty Boo Mansion - Section 1", "TeresaConveyorStageMap1.szs"},
            {"3-4 Pretty Plaza Panic - Section 1", "ShortGardenStageMap1.szs"},
            {"3-4 Pretty Plaza Panic - Sky Section", "CloudBonusCZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 1", "DokanAquariumStageMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 2", "DokanAquariumBZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 3", "DokanAquariumCZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 4", "DokanAquariumDZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 5", "DokanAquariumGoalZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Bonus Room", "GoldRoomUnderSeaZoneMap1.szs"},
            {"3-6 Mount Must Dash - Section 1", "DashRidgeStageMap1.szs"},
            {"3-6 Mount Must Dash - Section 2", "DashRidgeGoalZoneMap1.szs"},
            {"3-7 Switchboard Falls - Section 1", "TruckWaterfallStageMap1.szs"},
            {"3-A Magikoopa Blockade - Section 1", "GateKeeperKameckLv1StageMap1.szs"},
            {"3-B A Banquet with Hisstocrat - Section 1","GateKeeperTentackLv1StageMap1.szs"},
            {"3-B A Banquet with Hisstocrat - Section 2","BossTentackZoneMap1.szs"},
            {"3-Castle The Bullet Bill Express Fairy Cutscene Section","DemoWorldClear03StageMap1.szs"},
            {"3-Toad Captain Toad Makes a Splash","KinopioBrigadeWaterStageMap1.szs"},
            {"3-Train The Bullet Bill Express - Section 2","TrainPunpun01ZoneMap1.szs"},
            {"3-Tran The Bullet Bill Express - Section 1","KillerExpressStageMap1.szs"},
            {"4-1 Ant Trooper Hill - Bonus Room","CrawlerHillDokanRoomZoneMap1.szs"},
            {"4-1 Ant Trooper Hill - Section 1","CrawlerHillStageMap1.szs"},
            {"4-2 Piranha Creeper Creek - Bonus Room","PipePackunDenBonusRoomZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 1","PipePackunDenStageMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 2","PipePackunDenFirstZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 3","PipePackunDenSecondZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 4","PipePackunDenThirdZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 5","PipePackunDenGoalZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Bonus Room","ChikaChikaBoomerangAoCoinZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Section 1","ChikaChikaBoomerangStageMap1.szs"},
            {"4-3 Beep Block Skyway - Section 2","ChikaChikaBoomerangAZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Section 3","ChikaChikaBoomerangBZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Section 4","ChikaChikaBoomerangCZoneMap1.szs"},
            {"4-4 Big Bounce Byway - Section 1","TrampolineHighlandStageMap1.szs"},
            {"4-5 Spikes Lost City - Bonus Room","GabonMountainBonusRoomZoneMap1.szs"},
            {"4-5 Spikes Lost City - Section 1","GabonMountainStageMap1.szs"},
            {"4-A Brolder Blockade - Section 1","GateKeeperGorobonLv1StageMap1.szs"},
            {"4-B Fire Bros Hideout 1 - Section 1","GateKeeperFireBrosLv1StageMap1.szs"},
            {"4-Castle Lava Rock Lair - Section 1","BossGorobonStageMap1.szs"},
            {"4-Castle Lava Rock Lair - Section 2","BossGorobonZoneMap1.szs"},
            {"4-Castle Lava Rock Lair Fairy Cutscene Section","DemoWorldClear04StageMap1.szs"},
            {"4-Mystery House Mad Dash - Section 1","MysteryHouseDashStageMap1.szs"},
            {"5-1 Sunshine Seaside - Section 1","NokonokoBeachStageMap1.szs"},
            {"5-2 Tricky Trapeze Theater - Bonus Room","TimerCoinRoomCircusZoneMap1.szs"},
            {"5-2 Tricky Trapeze Theater - Bonus Section","SwingCircusBonusZoneMap1.szs"},
            {"5-2 Tricky Trapeze Theater - Section 1","SwingCircusStageMap1.szs"},
            {"5-3 Backstreet Bustle - Section 1","ShortMultiLiftStageMap1.szs"},
            {"5-4 Sprawling Savanna - Section 1","SavannaRockStageMap1.szs"},
            {"5-5 Bob-ombs Below - Section 1","BombCaveStageMap1.szs"},
            {"5-5 Bob-ombs Below - Sky Section","CloudBonusRoomZoneMap1.szs"},
            {"5-6 Cakewalk Flip - Section 1","JumpFlipSweetsStageMap1.szs"},
            {"5-7 Searchlight Sneak - Section 1","SneakingLightStageMap1.szs"},
            {"5-A Chargin Chuck Blockade Is Back - Section 1","GateKeeperBullLv2StageMap1.szs"},
            {"5-B Fire Bros Hideout 2 - Section 1","GateKeeperFireBrosLv2StageMap1.szs"},
            {"5-Castle King Ka-thunks Castle - Section 1","BossWackunFortressFirstZoneMap1.szs"},
            {"5-Castle King Ka-thunks Castle - Section 2","BossWackunFortressStageMap1.szs"},
            {"5-Castle King Ka-thunks Castle - Section 3","BossWackunFortressBossZoneMap1.szs"},
            {"5-Castle King Ka-thunks Castle Fairy Cutscene Section","DemoWorldClear05StageMap1.szs"},
            {"5-Toad Captain Toad Plays Peek-a-Boo","KinopioBrigadeTeresaStageMap1.szs"},
            {"5-Train Coin Express - Section 1","GoldenExpressStageMap1.szs"},
            {"6-1 Clear Pipe Cruise - Section 1","RouteDokanTourStageMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 1","WeavingShipStageMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 2","WeavingShip00ZoneMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 3","WeavingShip01ZoneMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 4","WeavingShip02ZoneMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 5","WeavingShipGoalZoneMap1.szs"},
            {"6-3 Hands-On Hall - Section 1","KarakuriCastleStageMap1.szs"},
            {"6-4 Deep Jungle Drift - Section 1","JungleCruiseStageMap1.szs"},
            {"6-5 Ty-Foo Flurries - Section 1","BlastSnowFieldStageMap1.szs"},
            {"6-6 Bullet Bill Base - Section 1","ClimbFortressStageMap1.szs"},
            {"6-7 Fuzzy Time Mine - Section 1","ChorobonTowerStageMap1.szs"},
            {"6-A Prince Bully Blockade - Section 1","GateKeeperKyupponLv1StageMap1.szs"},
            {"6-B Fire Bros Hideout 3 - Section 1","GateKeeperFireBrosLv3StageMap1.szs"},
            {"6-C Motley Bossblobs Big Battle - Section 1","GateKeeperBossBunretsuLv1StageMap1.szs"},
            {"6-C Motley Bossblobs Big Battle - Section 2","BossBunretsuZoneMap1.szs"},
            {"6-Castle Bowsers Bob-omb Brigade Fairy Cutscene Section","DemoWorldClear06StageMap1.szs"},
            {"6-Mystery House Throwdown - Section 1","MysteryHouseBallStageMap1.szs"},
            {"6-Tank Bowsers Bob-omb Brigade  -Section 2","TankBunbun02ZoneMap1.szs"},
            {"6-Tank Bowsers Bob-omb Brigade - Section 1","BombTankStageMap1.szs"},
            {":-1 Spiky Spike Bridge - Bonus  Room","ClimbMysteryBoxAZoneMap1.szs"},
            {":-1 Spiky Spike Bridge - Section 1","NeedleBridgeStageMap1.szs"},
            {":-2 Plessies Dune Downhill - Section 1","DownDesertStageMap1.szs"},
            {":-3 Cookie Cogworks - Section 1","GearSweetsStageMap1.szs"},
            {":-4 Footlight Lane - Section 1","EchoRoadStageMap1.szs"},
            {":-5 Deepwater Dungeon - Section 1","WaterElevatorCaveStageMap1.szs"},
            {":-5 Deepwater Dungeon - Sky Section","CloudBonusWaterElevatorCaveZoneMap1.szs"},
            {":-6 A Beam in the Dark - Section 1","DarknessHauntedHouseStageMap1.szs"},
            {":-7 Grumblump Inferno - Section 1","GotogotonValleyStageMap1.szs"},
            {":-A Motley Bossblobs Encore - Section 1","GateKeeperBossBunretsuLv2StageMap1.szs"},
            {":-A Motley Bossblobs Encore - Section 2","BossBunretsu02ZoneMap1.szs"},
            {":-B Hisstocrat Returns - Section 1","GateKeeperTentackLv2StageMap1.szs"},
            {":-B Hisstocrat Returns - Section 2","BossTentack02ZoneMap1.szs"},
            {":-Castle The Great Tower of Bowser Land - Section 1","KoopaLastStageMap1.szs"},
            {":-Castle The Great Tower of Bowser Land - Section 2","KoopaLastAZoneMap1.szs"},
            {":-Castle The Great Tower of Bowser Land - Section 3","KoopaLastBZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 1","MysteryHouseClimbStageMap1.szs"},
            {":-Mystery House Claw Climb - Section 2","MysteryClimbAZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 3","MysteryClimbBZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 4","MysteryClimbCZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 5","MysteryClimbDZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 6","MysteryClimbEZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 7","MysteryClimbFZoneMap1.szs"},
            {":-Train The Bowser Express - Section 1","EnemyExpressStageMap1.szs"},
            {":-Train The Bowser Express - Section 2","TrainPunpun02ZoneMap1.szs"},
            {"' - A Brolder Blockade Is Back - Section 1","GateKeeperGorobonLv2StageMap1.szs"},
            {"' Goal Pole Section","CastleGoalZoneMap1.szs"},
            {"' Goal Pole Section 2","GKCastleGoalZoneMap1.szs"},
            {"' Start Cutscene Section","DemoCourseStartCastleStageMap1.szs"},
            {"'-1 Fort Fire Bros - Bonus Section","FireBrosFortressBonusZoneMap1.szs"},
            {"'-1 Fort Fire Bros - Section 1","FireBrosFortressStageMap1.szs"},
            {"'-2 Switchblack Ruins - Section 1","DarkFlipPanelStageMap1.szs"},
            {"'-3 Red-Hot Run - Section 1","ShortAmidaStageMap1.szs"},
            {"'-4 Boiling Blue Bully Belt - Bonus Room","DonketsuArrowStepBonusRoomZoneMap1.szs"},
            {"'-4 Boiling Blue Bully Belt - Section 1","DonketsuArrowStepStageMap1.szs"},
            {"'-4 Boiling Blue Bully Belt - Section 2","DonketsuArrowStepGoalZoneMap1.szs"},
            {"'-5 Trick Trap Tower - Section 1","ZigzagBuildingStageMap1.szs"},
            {"'-6 Rammerhead Reef - Section 1","SyumockSpotStageMap1.szs"},
            {"'-6 Rammerhead Reef - Section 2","SyumockSpotAZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 3","SyumockSpotBZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 4","SyumockSpotCZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 5","SyumockSpotDZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 6","SyumockSpotGoalZoneMap1.szs"},
            {"'-7 Simmering Lava Lake - Section 1","RagingMagmaStageMap1.szs"},
            {"'-7 Simmering Lava Lake - Section 2","RagingMagmaAZoneMap1.szs"},
            {"'-B Prince Bully Blockade Is Back - Section 1","GateKeeperKyupponLv2StageMap1.szs"},
            {"'-C Fire Bros Hideout 4 - Section 1","GateKeeperFireBrosLv4StageMap1.szs"},
            {"'-Castle Bowsers Lava Lake Keep - Section 1","KoopaChaseLv2StageMap1.szs"},
            {"'-Castle Bowsers Lava Lake Keep - Section 2","KoopaChaseLv2ZoneMap1.szs"},
            {"'-Castle Bowsers Lava Lake Keep Fairy Catch Cutscene Section","DemoKoopaCatchFairyAgainStageMap1.szs"},
            {"'-Toad Captain Toad Gets Thwomped","KinopioBrigadeConveyorStageMap1.szs"},
            {"Common Blockade Objects","GateKeeperInsideZoneMap1.szs"},
            {"Common Blockade Skymap","GateKeeperOutsideZoneMap1.szs"},
            {"Common Mystery House Entrance","MysteryHouseEntranceZoneMap1.szs"},
            {"Common Mystery House Entrance 2","MysteryHouseEntranceLv2ZoneMap1.szs"},
            {"Common Mystery House Entrance 3","MysteryHouseEntranceLv3ZoneMap1.szs"},
            {"Common Toad House Model","KinopioRoomAZoneMap1.szs"},
            {"&-Crown Champions Road - Section 1","ChampionshipStageMap1.szs"},
            {"&-Crown Champions Road - Section 2","ChampionshipAZoneMap1.szs"},
            {"&-Crown Champions Road - Section 3","ChampionshipBZoneMap1.szs"},
            {"&-Crown Champions Road - Section 4","ChampionshipCZoneMap1.szs"},
            {"&-Crown Champions Road - Section 5","ChampionshipDZoneMap1.szs"},
            {"&-Crown Champions Road - Section 6","ChampionshipFZoneMap1.szs"},
            {"&-Crown Champions Road - Section 7","ChampionshipGoalZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 1","MysteryHouseMaxStageMap1.szs"},
            {"&-Mystery House Marathon - Section 2","MysteryMaxBlastSnowFieldZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 3","MysteryMaxBlockLandZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 4","MysteryMaxBossGorobonZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 5","MysteryMaxClimbFortressZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 6","MysteryMaxDashRidgeZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 7","MysteryMaxDonketsuArrowStepZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 8","MysteryMaxEchoRoadZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 9","MysteryMaxFlipCircusZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 10","MysteryMaxMysteryBallAZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 11","MysteryMaxMysteryBallCZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 12","MysteryMaxMysteryBallDZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 13","MysteryMaxMysteryClimbBZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 14","MysteryMaxMysteryClimbEZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 15","MysteryMaxMysteryClimbFZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 16","MysteryMaxMysteryDashGZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 17","MysteryMaxMysteryDashIZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 18","MysteryMaxMysteryDashJZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 19","MysteryMaxMysteryEnemyZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 20","MysteryMaxNeedleBridgeZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 21","MysteryMaxNokonokoCaveZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 22","MysteryMaxPipePackunDenZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 23","MysteryMaxSneakingLightZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 24","MysteryMaxTeresaConveyorZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 25","MysteryMaxTrampolineHighlandZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 26","MysteryMaxWheelCanyonZoneMap1.szs"},
            {"&-Toad Captain Toads Fiery Finale","KinopioBrigadeInfernoStageMap1.szs"},
            {"End Cutscene Section 1","DemoEndRollStageMap1.szs"},
            {"End Cutscene Section 2","DemoEndRollEndStageMap1.szs"},
            {"Final Castle Start Cutscene Section","DemoCourseStartKoopaCastleLastStageMap1.szs"},
            {"%-1 Switch Shock Circus - Bonus Room","ArrangeFlipCircusBonusRoomZoneMap1.szs"},
            {"%-1 Switch Shock  Circus - Section 1","ArrangeFlipCircusStageMap1.szs"},
            {"%-10 Honeycomb Skyway - Section 1","ArrangeHexScrollStageMap1.szs"},
            {"%-11 Spiky Spike Bridge Sneak - Section 1","ArrangeNeedleBridgeStageMap1.szs"},
            {"%-12 Boss Blitz - Boom Booom Section","TankBunbun03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Hisstocrats","BossTentack03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Motley Bossblob","BossBunretsu03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Pom Pom Section","TrainPunpun03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Section 1","ArrangeBossParadeStageMap1.szs"},
            {"%-2 Floating Fuzzy Time Mine - Section 1","ArrangeChorobonTowerStageMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 0","ArrangePipePackunDenStageMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 1","ArrangePipePackunDenFirstZoneMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 2","ArrangePipePackunDenThirdZoneMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 3","ArrangePipePackunDenGoalZoneMap1.szs"},
            {"%-4 Faster Fort Fire Bros - Section 1","ArrangeFireBrosFortressStageMap1.szs"},
            {"%-5 Sprawling Savanna Rabbit Run - Section 1","ArrangeSavannaRockStageMap1.szs"},
            {"%-6 Shiftier Boo Mansion - Section 1","ArrangeTeresaConveorStageMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 1","ArrangeDokanAquariumStageMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 2","ArrangeAquariumAZoneMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 3","ArrangeAquariumBZoneMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 4","ArrangeAquariumCZoneMap1.szs"},
            {"%-8 Blast Block Skyway - Section 1","ArrangeChikaChikaBoomerangStageMap1.szs"},
            {"%-8 Blast Block Skyway - Section 2","ArrangeChikaAZoneMap1.szs"},
            {"%-8 Blast Block Skyway - Section 3","ArrangeChikaBZoneMap1.szs"},
            {"%-8 Blast Block Skyway - Section 4","ArrangeChikaCZoneMap1.szs"},
            {"%-9 Towering Sunshine Seaside - Section 1","ArrangeNokonokoBeachStageMap1.szs"},
            {"Game Over Cutscene Section","DemoGameOverStageMap1.szs"},
            {"Golden Train Stage Start Cutscene Section","DemoCourseStartTrainGoldStageMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Bonus Room","ArrangeRotateFieldDoremiZoneMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Section 1","ArrangeRotateFieldStageMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Section 2","ArrangeRotateFieldBZoneMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Section 3","ArrangeRotateFieldGoalZoneMap1.szs"},
            {"$-2  Spiky Mount Beanpole - Bonus Room","ArrangeClimbMountainDokanZoneMap1.szs"},
            {"$-2 Spiky Mount Beanpole - Section 1","ArrangeClimbMountainStageMap1.szs"},
            {"$-3 Deep-Black Jungle Drift - Section 1","ArrangeJungleCruiseStageMap1.szs"},
            {"$-4 Trouble in Shadow-Play Ally - Section 1","ArrangeShadowTunnelStageMap1.szs"},
            {"$-5 Back to Hands-On Hall - Section 1","ArrangeKarakuriCastleStageMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 1","ArrangeWeavingShip00ZoneMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 1-2","ArrangeWeavingShipStageMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 2","ArrangeWeavingShip02ZoneMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 3","ArrangeWeavingShipGoalZoneMap1.szs"},
            {"$-7 Broken Blue Bully Belt - Section 1","ArrangeDonketsuArrowStepStageMap1.szs"},
            {"$-7 Broken Blue Bully Belt - Section 2","ArrangeDonketsuArrowStepZoneMap1.szs"},
            {"$-Mystery House Brawl - Section 1","ArrangeMysteryHouseEnemyStageMap1.szs"},
            {"Opening Cutscene Section 1","DemoOpeningStageMap1.szs"},
            {"Opening Cutscene Section 2","DemoOpeningExitStageMap1.szs"},
            {"Pipe Stage Cutscene Section","DemoOpeningDokanStageMap1.szs"},
            {"Roulette Minigame Room","RouletteRoomZoneMap1.szs"},
            {"Sprixie House","FairyHouseZoneMap1.szs"},
            {"Sprixie House Lava Backdrop","FairyHouseLavaStageMap1.szs"},
            {"Sprixie House Night Backdrop","FairyHouseNightStageMap1.szs"},
            {"Sprixie House Overworld Backdrop","FairyHouseBlueStageMap1.szs"},
            {"Sprixie House Underground Backdrop","FairyHouseInsideStageMap1.szs"},
            {"\"-1 Rainbow Run - Bonus Room","RainbowRoadBonusZoneMap1.szs"},
            {"\"-1 Rainbow Run - Section 1","RainbowRoadStageMap1.szs"},
            {"\"-1 Rainbow Run - Sky Section","CloudBonusZeldaZoneMap1.szs"},
            {"\"-2 Super Galaxy - Section 1","GalaxyRoadStageMap1.szs"},
            {"\"-2 Super Galaxy Rosalina Cutscene Section","DemoEndRollRosettaStageMap1.szs"},
            {"\"-3 Rolling Ride Run - Bonus Room","WheelMysteryBoxZoneMap1.szs"},
            {"\"-3 Rolling Ride Run - Section 1","WheelCanyonStageMap1.szs"},
            {"\"-4 The Great Goal Pole - Section 1","GoalPoleRunawayStageMap1.szs"},
            {"\"-5 Super Block Land - Section 1","BlockLandStageMap1.szs"},
            {"\"-6 Honeycomb Starway - Section 1","HexScrollStageMap1.szs"},
            {"\"-7 Gargantuan Grotto - Bonus Room","GiantAoCoinZoneMap1.szs"},
            {"\"-7 Gargantuan Grotto - Section 1","GiantUnderGroundStageMap1.szs"},
            {"\"-8 Peepas Fog Bog - Bonus Room","TerenFogGoalZoneMap1.szs"},
            {"\"-8 Peepas Fog Bog - Section 1","TerenFogStageMap1.szs"},
            {"\"-8 Peepas Fog Bog - Section 2","TerenFogBridgeZoneMap1.szs"},
            {"\"-8 Peepas Fog Bog - Section 3","TerenFogMysteryZoneMap1.szs"},
            {"\"-9 Cosmic Cannon Cluster - Section 1","BoxKillerStageMap1.szs"},
            {"\"-Toad Captain Toad Takes a Spin","KinopioBrigadeRotateRoomStageMap1.szs"},
            {"Title Screen","CommonTitleDemoZoneMap1.szs"},
            {"Title Screen Objects Variation 1","TitleDemo00StageMap1.szs"},
            {"Title Screen Objects Variation 2","TitleDemo01StageMap1.szs"},
            {"Title Screen Objects Variation 3","TitleDemo02StageMap1.szs"},
            {"Title Screen Objects Variation 4","TitleDemo03StageMap1.szs"},
            {"Title Screen Objects Variation 5","TitleDemo04StageMap1.szs"},
            {"Title Screen Objects Variation 6","TitleDemo05StageMap1.szs"},
            {"Toad House Blue Sky 1","KinopioHouseBlueZoneMap1.szs"},
            {"Toad House Blue Sky 2","KinopioHouseLv1BlueStageMap1.szs"},
            {"Toad House Blue Sky 2-2","KinopioHouseLv2BlueStageMap1.szs"},
            {"Toad House Blue Sky 3","KinopioHouseLv3BlueStageMap1.szs"},
            {"Toad House Lava Sky 1","KinopioHouseLavaZoneMap1.szs"},
            {"Toad House Lava Sky 2","KinopioHouseLv3LavaStageMap1.szs"},
            {"Toad House Night Sky 1","KinopioHouseLv3NightStageMap1.szs"},
            {"Toad House Night Sky 2","KinopioHouseNightZoneMap1.szs"},
            {"Toad House Underground Sky 1","KinopioHouseInsideZoneMap1.szs"},
            {"Toad House Underground Sky 2","KinopioHouseLv1InsideStageMap1.szs"},
            {"Unused Colour Panel Room","DoremiRoomBZoneMap1.szs"},
            {"World 1 Castle Start Cutscene Section","DemoCourseStartKoopaCastleStageMap1.szs"},
            {"World 1 Map","CourseSelectW1ZoneMap1.szs"},
            {"World 2 Map","CourseSelectW2ZoneMap1.szs"},
            {"World 2 Tank Stage Start Cutscene Section","DemoCourseStartTankStageMap1.szs"},
            {"World 3 Map","CourseSelectW3ZoneMap1.szs"},
            {"World 3 Train Stage Start Cutscene Section","DemoCourseStartTrainStageMap1.szs"},
            {"World 4 Map","CourseSelectW4ZoneMap1.szs"},
            {"World 5 Map","CourseSelectW5ZoneMap1.szs"},
            {"World 6 Map","CourseSelectW6ZoneMap1.szs"},
            {"World 6 Tank Stage Start Cutscene Section","DemoCourseStartTankBombStageMap1.szs"},
            {"World ' Map","CourseSelectW7ZoneMap1.szs"},
            {"World : Map","CourseSelectW8ZoneMap1.szs"},
            {"World : Train Stage Start Cutscene Section","DemoCourseStartTrainEnemyStageMap1.szs"},
            {"World & Map","CourseSelectStageMap1.szs"},
            {"World \"%$ Map","CourseSelectS1ZoneMap1.szs"}
        };
            string Name = Database.FirstOrDefault(x => x.Value == LevelFileName).Key;
            return Name;
        }
        public static string GetLevelFileName(string LevelName)
        {
            Dictionary<string, string> Database = new Dictionary<string, string>
        {
            {"1-1 Super Bell Hill - Section 1", "EnterCatMarioStageMap1.szs" },
            {"1-2 Koopa Troopa Cave - Section 1", "NokonokoCaveStageMap1.szs"},
            {"1-2 Koopa Troopa Cave - Bonus Room", "GoldRoomKouraZoneMap1.szs"},
            {"1-3 Mount Beanpole - Section 1", "ClimbMountainStageMap1.szs"},
            {"1-3 Mount Beanpole - Sky Section", "CloudBonusEZoneMap1.szs" },
            {"1-3 Mount Beanpole - Bonus Room", "AoCoinFirstZoneMap1.szs" },
            {"1-4 Plessies Plunging Falls - Section 1", "DownRiverStageMap1.szs" },
            {"1-5 Switch Scramble Circus - Section 1", "FlipCircusStageMap1.szs"},
            {"1-5 Switch Scramble Circus - Bonus Room", "FlipCircusBonusRoomZoneMap1.szs" },
            {"1-A Chargin Chuck Blockade - Section 1", "GateKeeperBullLv1StageMap1.szs"},
            {"1-Castle Bowsers Highway Showdown - Section 1", "KoopaChaseLv1StageMap1.szs"},
            {"1-Castle Bowsers Highway Showdown Fairy Cutscene Section", "DemoWorldClear01StageMap1.szs"},
            {"1-Toad Captain Toad Goes Forth", "KinopioBrigadeTentenStageMap1.szs"},
            {"2-1 Conkdor Canyon - Section 1", "SideWaveDesertStageMap1.szs"},
            {"2-1 Conkdor Canyon - Bonus Room", "GoldRoomWaterfallZoneMap1.szs" },
            {"2-2 Puffprod Peaks - Section 1", "TouchAndMikeStageMap1.szs"},
            {"2-2 Puffprod Peaks - Section 2", "TouchAndMikeSecondZoneMap1.szs"},
            {"2-2 Puffprod Peaks - Bonus Room", "TouchAndMikeBonusRoomZoneMap1.szs"},
            {"2-2 Puffroad Peaks - Sky Section", "CloudBonusTouchAndMikeZoneMap1.szs"},
            {"2-3 Shadow-Play Alley - Section 1", "ShadowTunnelStageMap1.szs"},
            {"2-4 Really Rolling Hills - Section 1", "RotateFieldStageMap1.szs"},
            {"2-4 Really Rolling Hills - Section 2", "RotateFieldBZoneMap1.szs"},
            {"2-4 Really Rolling Hills - Section 3", "RotateFieldGoalZoneMap1.szs"},
            {"2-4 Really Rolling Hills - Bonus Room", "RotateFieldDoremiZoneMap1.szs"},
            {"2-5 Double Cherry Pass - Section 1", "DoubleMarioFieldStageMap1.szs" },
            {"2-A Big Galoomba Blockade - Section 1", "GateKeeperKuribonLv1StageMap1.szs"},
            {"2-Castle Bowsers Bullet Bill Brigade Fairy Cutscene Section", "DemoWorldClear02StageMap1.szs"},
            {"2-Mystery House Melee - Basic Room", "MysteryHouseEnemyZoneMap1.szs"},
            {"2-Mystery House Melee - Section 1", "MysteryHouseEnemyStageMap1.szs"},
            {"2-Tank Bowsers Bullet Bill Brigade - Section 1", "KillerTankStageMap1.szs"},
            {"2-Tank Bowsers Bullet Bill Brigade - Section 2", "TankBunbun01ZoneMap1.szs"},
            {"3-1 Snowball Park - Section 1", "SnowBallParkStageMap1.szs"},
            {"3-2 Chain-Link Charge - Section 1", "ClimbWirenetStageMap1.szs"},
            {"3-3 Shifty Boo Mansion - Section 1", "TeresaConveyorStageMap1.szs"},
            {"3-4 Pretty Plaza Panic - Section 1", "ShortGardenStageMap1.szs"},
            {"3-4 Pretty Plaza Panic - Sky Section", "CloudBonusCZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 1", "DokanAquariumStageMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 2", "DokanAquariumBZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 3", "DokanAquariumCZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 4", "DokanAquariumDZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Section 5", "DokanAquariumGoalZoneMap1.szs"},
            {"3-5 Pipeline Lagoon - Bonus Room", "GoldRoomUnderSeaZoneMap1.szs"},
            {"3-6 Mount Must Dash - Section 1", "DashRidgeStageMap1.szs"},
            {"3-6 Mount Must Dash - Section 2", "DashRidgeGoalZoneMap1.szs"},
            {"3-7 Switchboard Falls - Section 1", "TruckWaterfallStageMap1.szs"},
            {"3-A Magikoopa Blockade - Section 1", "GateKeeperKameckLv1StageMap1.szs"},
            {"3-B A Banquet with Hisstocrat - Section 1","GateKeeperTentackLv1StageMap1.szs"},
            {"3-B A Banquet with Hisstocrat - Section 2","BossTentackZoneMap1.szs"},
            {"3-Castle The Bullet Bill Express Fairy Cutscene Section","DemoWorldClear03StageMap1.szs"},
            {"3-Toad Captain Toad Makes a Splash","KinopioBrigadeWaterStageMap1.szs"},
            {"3-Train The Bullet Bill Express - Section 2","TrainPunpun01ZoneMap1.szs"},
            {"3-Tran The Bullet Bill Express - Section 1","KillerExpressStageMap1.szs"},
            {"4-1 Ant Trooper Hill - Bonus Room","CrawlerHillDokanRoomZoneMap1.szs"},
            {"4-1 Ant Trooper Hill - Section 1","CrawlerHillStageMap1.szs"},
            {"4-2 Piranha Creeper Creek - Bonus Room","PipePackunDenBonusRoomZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 1","PipePackunDenStageMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 2","PipePackunDenFirstZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 3","PipePackunDenSecondZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 4","PipePackunDenThirdZoneMap1.szs"},
            {"4-2 Piranha Creeper Creek - Section 5","PipePackunDenGoalZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Bonus Room","ChikaChikaBoomerangAoCoinZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Section 1","ChikaChikaBoomerangStageMap1.szs"},
            {"4-3 Beep Block Skyway - Section 2","ChikaChikaBoomerangAZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Section 3","ChikaChikaBoomerangBZoneMap1.szs"},
            {"4-3 Beep Block Skyway - Section 4","ChikaChikaBoomerangCZoneMap1.szs"},
            {"4-4 Big Bounce Byway - Section 1","TrampolineHighlandStageMap1.szs"},
            {"4-5 Spikes Lost City - Bonus Room","GabonMountainBonusRoomZoneMap1.szs"},
            {"4-5 Spikes Lost City - Section 1","GabonMountainStageMap1.szs"},
            {"4-A Brolder Blockade - Section 1","GateKeeperGorobonLv1StageMap1.szs"},
            {"4-B Fire Bros Hideout 1 - Section 1","GateKeeperFireBrosLv1StageMap1.szs"},
            {"4-Castle Lava Rock Lair - Section 1","BossGorobonStageMap1.szs"},
            {"4-Castle Lava Rock Lair - Section 2","BossGorobonZoneMap1.szs"},
            {"4-Castle Lava Rock Lair Fairy Cutscene Section","DemoWorldClear04StageMap1.szs"},
            {"4-Mystery House Mad Dash - Section 1","MysteryHouseDashStageMap1.szs"},
            {"5-1 Sunshine Seaside - Section 1","NokonokoBeachStageMap1.szs"},
            {"5-2 Tricky Trapeze Theater - Bonus Room","TimerCoinRoomCircusZoneMap1.szs"},
            {"5-2 Tricky Trapeze Theater - Bonus Section","SwingCircusBonusZoneMap1.szs"},
            {"5-2 Tricky Trapeze Theater - Section 1","SwingCircusStageMap1.szs"},
            {"5-3 Backstreet Bustle - Section 1","ShortMultiLiftStageMap1.szs"},
            {"5-4 Sprawling Savanna - Section 1","SavannaRockStageMap1.szs"},
            {"5-5 Bob-ombs Below - Section 1","BombCaveStageMap1.szs"},
            {"5-5 Bob-ombs Below - Sky Section","CloudBonusRoomZoneMap1.szs"},
            {"5-6 Cakewalk Flip - Section 1","JumpFlipSweetsStageMap1.szs"},
            {"5-7 Searchlight Sneak - Section 1","SneakingLightStageMap1.szs"},
            {"5-A Chargin Chuck Blockade Is Back - Section 1","GateKeeperBullLv2StageMap1.szs"},
            {"5-B Fire Bros Hideout 2 - Section 1","GateKeeperFireBrosLv2StageMap1.szs"},
            {"5-Castle King Ka-thunks Castle - Section 1","BossWackunFortressFirstZoneMap1.szs"},
            {"5-Castle King Ka-thunks Castle - Section 2","BossWackunFortressStageMap1.szs"},
            {"5-Castle King Ka-thunks Castle - Section 3","BossWackunFortressBossZoneMap1.szs"},
            {"5-Castle King Ka-thunks Castle Fairy Cutscene Section","DemoWorldClear05StageMap1.szs"},
            {"5-Toad Captain Toad Plays Peek-a-Boo","KinopioBrigadeTeresaStageMap1.szs"},
            {"5-Train Coin Express - Section 1","GoldenExpressStageMap1.szs"},
            {"6-1 Clear Pipe Cruise - Section 1","RouteDokanTourStageMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 1","WeavingShipStageMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 2","WeavingShip00ZoneMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 3","WeavingShip01ZoneMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 4","WeavingShip02ZoneMap1.szs"},
            {"6-2 Spooky Seasick Wreck - Section 5","WeavingShipGoalZoneMap1.szs"},
            {"6-3 Hands-On Hall - Section 1","KarakuriCastleStageMap1.szs"},
            {"6-4 Deep Jungle Drift - Section 1","JungleCruiseStageMap1.szs"},
            {"6-5 Ty-Foo Flurries - Section 1","BlastSnowFieldStageMap1.szs"},
            {"6-6 Bullet Bill Base - Section 1","ClimbFortressStageMap1.szs"},
            {"6-7 Fuzzy Time Mine - Section 1","ChorobonTowerStageMap1.szs"},
            {"6-A Prince Bully Blockade - Section 1","GateKeeperKyupponLv1StageMap1.szs"},
            {"6-B Fire Bros Hideout 3 - Section 1","GateKeeperFireBrosLv3StageMap1.szs"},
            {"6-C Motley Bossblobs Big Battle - Section 1","GateKeeperBossBunretsuLv1StageMap1.szs"},
            {"6-C Motley Bossblobs Big Battle - Section 2","BossBunretsuZoneMap1.szs"},
            {"6-Castle Bowsers Bob-omb Brigade Fairy Cutscene Section","DemoWorldClear06StageMap1.szs"},
            {"6-Mystery House Throwdown - Section 1","MysteryHouseBallStageMap1.szs"},
            {"6-Tank Bowsers Bob-omb Brigade  -Section 2","TankBunbun02ZoneMap1.szs"},
            {"6-Tank Bowsers Bob-omb Brigade - Section 1","BombTankStageMap1.szs"},
            {":-1 Spiky Spike Bridge - Bonus  Room","ClimbMysteryBoxAZoneMap1.szs"},
            {":-1 Spiky Spike Bridge - Section 1","NeedleBridgeStageMap1.szs"},
            {":-2 Plessies Dune Downhill - Section 1","DownDesertStageMap1.szs"},
            {":-3 Cookie Cogworks - Section 1","GearSweetsStageMap1.szs"},
            {":-4 Footlight Lane - Section 1","EchoRoadStageMap1.szs"},
            {":-5 Deepwater Dungeon - Section 1","WaterElevatorCaveStageMap1.szs"},
            {":-5 Deepwater Dungeon - Sky Section","CloudBonusWaterElevatorCaveZoneMap1.szs"},
            {":-6 A Beam in the Dark - Section 1","DarknessHauntedHouseStageMap1.szs"},
            {":-7 Grumblump Inferno - Section 1","GotogotonValleyStageMap1.szs"},
            {":-A Motley Bossblobs Encore - Section 1","GateKeeperBossBunretsuLv2StageMap1.szs"},
            {":-A Motley Bossblobs Encore - Section 2","BossBunretsu02ZoneMap1.szs"},
            {":-B Hisstocrat Returns - Section 1","GateKeeperTentackLv2StageMap1.szs"},
            {":-B Hisstocrat Returns - Section 2","BossTentack02ZoneMap1.szs"},
            {":-Castle The Great Tower of Bowser Land - Section 1","KoopaLastStageMap1.szs"},
            {":-Castle The Great Tower of Bowser Land - Section 2","KoopaLastAZoneMap1.szs"},
            {":-Castle The Great Tower of Bowser Land - Section 3","KoopaLastBZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 1","MysteryHouseClimbStageMap1.szs"},
            {":-Mystery House Claw Climb - Section 2","MysteryClimbAZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 3","MysteryClimbBZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 4","MysteryClimbCZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 5","MysteryClimbDZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 6","MysteryClimbEZoneMap1.szs"},
            {":-Mystery House Claw Climb - Section 7","MysteryClimbFZoneMap1.szs"},
            {":-Train The Bowser Express - Section 1","EnemyExpressStageMap1.szs"},
            {":-Train The Bowser Express - Section 2","TrainPunpun02ZoneMap1.szs"},
            {"' - A Brolder Blockade Is Back - Section 1","GateKeeperGorobonLv2StageMap1.szs"},
            {"' Goal Pole Section","CastleGoalZoneMap1.szs"},
            {"' Goal Pole Section 2","GKCastleGoalZoneMap1.szs"},
            {"' Start Cutscene Section","DemoCourseStartCastleStageMap1.szs"},
            {"'-1 Fort Fire Bros - Bonus Section","FireBrosFortressBonusZoneMap1.szs"},
            {"'-1 Fort Fire Bros - Section 1","FireBrosFortressStageMap1.szs"},
            {"'-2 Switchblack Ruins - Section 1","DarkFlipPanelStageMap1.szs"},
            {"'-3 Red-Hot Run - Section 1","ShortAmidaStageMap1.szs"},
            {"'-4 Boiling Blue Bully Belt - Bonus Room","DonketsuArrowStepBonusRoomZoneMap1.szs"},
            {"'-4 Boiling Blue Bully Belt - Section 1","DonketsuArrowStepStageMap1.szs"},
            {"'-4 Boiling Blue Bully Belt - Section 2","DonketsuArrowStepGoalZoneMap1.szs"},
            {"'-5 Trick Trap Tower - Section 1","ZigzagBuildingStageMap1.szs"},
            {"'-6 Rammerhead Reef - Section 1","SyumockSpotStageMap1.szs"},
            {"'-6 Rammerhead Reef - Section 2","SyumockSpotAZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 3","SyumockSpotBZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 4","SyumockSpotCZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 5","SyumockSpotDZoneMap1.szs"},
            {"'-6 Rammerhead Reef - Section 6","SyumockSpotGoalZoneMap1.szs"},
            {"'-7 Simmering Lava Lake - Section 1","RagingMagmaStageMap1.szs"},
            {"'-7 Simmering Lava Lake - Section 2","RagingMagmaAZoneMap1.szs"},
            {"'-B Prince Bully Blockade Is Back - Section 1","GateKeeperKyupponLv2StageMap1.szs"},
            {"'-C Fire Bros Hideout 4 - Section 1","GateKeeperFireBrosLv4StageMap1.szs"},
            {"'-Castle Bowsers Lava Lake Keep - Section 1","KoopaChaseLv2StageMap1.szs"},
            {"'-Castle Bowsers Lava Lake Keep - Section 2","KoopaChaseLv2ZoneMap1.szs"},
            {"'-Castle Bowsers Lava Lake Keep Fairy Catch Cutscene Section","DemoKoopaCatchFairyAgainStageMap1.szs"},
            {"'-Toad Captain Toad Gets Thwomped","KinopioBrigadeConveyorStageMap1.szs"},
            {"Common Blockade Objects","GateKeeperInsideZoneMap1.szs"},
            {"Common Blockade Skymap","GateKeeperOutsideZoneMap1.szs"},
            {"Common Mystery House Entrance","MysteryHouseEntranceZoneMap1.szs"},
            {"Common Mystery House Entrance 2","MysteryHouseEntranceLv2ZoneMap1.szs"},
            {"Common Mystery House Entrance 3","MysteryHouseEntranceLv3ZoneMap1.szs"},
            {"Common Toad House Model","KinopioRoomAZoneMap1.szs"},
            {"&-Crown Champions Road - Section 1","ChampionshipStageMap1.szs"},
            {"&-Crown Champions Road - Section 2","ChampionshipAZoneMap1.szs"},
            {"&-Crown Champions Road - Section 3","ChampionshipBZoneMap1.szs"},
            {"&-Crown Champions Road - Section 4","ChampionshipCZoneMap1.szs"},
            {"&-Crown Champions Road - Section 5","ChampionshipDZoneMap1.szs"},
            {"&-Crown Champions Road - Section 6","ChampionshipFZoneMap1.szs"},
            {"&-Crown Champions Road - Section 7","ChampionshipGoalZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 1","MysteryHouseMaxStageMap1.szs"},
            {"&-Mystery House Marathon - Section 2","MysteryMaxBlastSnowFieldZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 3","MysteryMaxBlockLandZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 4","MysteryMaxBossGorobonZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 5","MysteryMaxClimbFortressZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 6","MysteryMaxDashRidgeZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 7","MysteryMaxDonketsuArrowStepZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 8","MysteryMaxEchoRoadZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 9","MysteryMaxFlipCircusZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 10","MysteryMaxMysteryBallAZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 11","MysteryMaxMysteryBallCZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 12","MysteryMaxMysteryBallDZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 13","MysteryMaxMysteryClimbBZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 14","MysteryMaxMysteryClimbEZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 15","MysteryMaxMysteryClimbFZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 16","MysteryMaxMysteryDashGZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 17","MysteryMaxMysteryDashIZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 18","MysteryMaxMysteryDashJZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 19","MysteryMaxMysteryEnemyZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 20","MysteryMaxNeedleBridgeZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 21","MysteryMaxNokonokoCaveZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 22","MysteryMaxPipePackunDenZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 23","MysteryMaxSneakingLightZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 24","MysteryMaxTeresaConveyorZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 25","MysteryMaxTrampolineHighlandZoneMap1.szs"},
            {"&-Mystery House Marathon - Section 26","MysteryMaxWheelCanyonZoneMap1.szs"},
            {"&-Toad Captain Toads Fiery Finale","KinopioBrigadeInfernoStageMap1.szs"},
            {"End Cutscene Section 1","DemoEndRollStageMap1.szs"},
            {"End Cutscene Section 2","DemoEndRollEndStageMap1.szs"},
            {"Final Castle Start Cutscene Section","DemoCourseStartKoopaCastleLastStageMap1.szs"},
            {"%-1 Switch Shock Circus - Bonus Room","ArrangeFlipCircusBonusRoomZoneMap1.szs"},
            {"%-1 Switch Shock  Circus - Section 1","ArrangeFlipCircusStageMap1.szs"},
            {"%-10 Honeycomb Skyway - Section 1","ArrangeHexScrollStageMap1.szs"},
            {"%-11 Spiky Spike Bridge Sneak - Section 1","ArrangeNeedleBridgeStageMap1.szs"},
            {"%-12 Boss Blitz - Boom Booom Section","TankBunbun03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Hisstocrats","BossTentack03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Motley Bossblob","BossBunretsu03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Pom Pom Section","TrainPunpun03ZoneMap1.szs"},
            {"%-12 Boss Blitz - Section 1","ArrangeBossParadeStageMap1.szs"},
            {"%-2 Floating Fuzzy Time Mine - Section 1","ArrangeChorobonTowerStageMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 0","ArrangePipePackunDenStageMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 1","ArrangePipePackunDenFirstZoneMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 2","ArrangePipePackunDenThirdZoneMap1.szs"},
            {"%-3 Piranha Creeper Creek after Dark - Section 3","ArrangePipePackunDenGoalZoneMap1.szs"},
            {"%-4 Faster Fort Fire Bros - Section 1","ArrangeFireBrosFortressStageMap1.szs"},
            {"%-5 Sprawling Savanna Rabbit Run - Section 1","ArrangeSavannaRockStageMap1.szs"},
            {"%-6 Shiftier Boo Mansion - Section 1","ArrangeTeresaConveorStageMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 1","ArrangeDokanAquariumStageMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 2","ArrangeAquariumAZoneMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 3","ArrangeAquariumBZoneMap1.szs"},
            {"%-7 Pipeline Boom Lagoon - Section 4","ArrangeAquariumCZoneMap1.szs"},
            {"%-8 Blast Block Skyway - Section 1","ArrangeChikaChikaBoomerangStageMap1.szs"},
            {"%-8 Blast Block Skyway - Section 2","ArrangeChikaAZoneMap1.szs"},
            {"%-8 Blast Block Skyway - Section 3","ArrangeChikaBZoneMap1.szs"},
            {"%-8 Blast Block Skyway - Section 4","ArrangeChikaCZoneMap1.szs"},
            {"%-9 Towering Sunshine Seaside - Section 1","ArrangeNokonokoBeachStageMap1.szs"},
            {"Game Over Cutscene Section","DemoGameOverStageMap1.szs"},
            {"Golden Train Stage Start Cutscene Section","DemoCourseStartTrainGoldStageMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Bonus Room","ArrangeRotateFieldDoremiZoneMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Section 1","ArrangeRotateFieldStageMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Section 2","ArrangeRotateFieldBZoneMap1.szs"},
            {"$-1 Night Falls on Really Rolling Hills - Section 3","ArrangeRotateFieldGoalZoneMap1.szs"},
            {"$-2  Spiky Mount Beanpole - Bonus Room","ArrangeClimbMountainDokanZoneMap1.szs"},
            {"$-2 Spiky Mount Beanpole - Section 1","ArrangeClimbMountainStageMap1.szs"},
            {"$-3 Deep-Black Jungle Drift - Section 1","ArrangeJungleCruiseStageMap1.szs"},
            {"$-4 Trouble in Shadow-Play Ally - Section 1","ArrangeShadowTunnelStageMap1.szs"},
            {"$-5 Back to Hands-On Hall - Section 1","ArrangeKarakuriCastleStageMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 1","ArrangeWeavingShip00ZoneMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 1-2","ArrangeWeavingShipStageMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 2","ArrangeWeavingShip02ZoneMap1.szs"},
            {"$-6 Gigantic Seasick Wreck - Section 3","ArrangeWeavingShipGoalZoneMap1.szs"},
            {"$-7 Broken Blue Bully Belt - Section 1","ArrangeDonketsuArrowStepStageMap1.szs"},
            {"$-7 Broken Blue Bully Belt - Section 2","ArrangeDonketsuArrowStepZoneMap1.szs"},
            {"$-Mystery House Brawl - Section 1","ArrangeMysteryHouseEnemyStageMap1.szs"},
            {"Opening Cutscene Section 1","DemoOpeningStageMap1.szs"},
            {"Opening Cutscene Section 2","DemoOpeningExitStageMap1.szs"},
            {"Pipe Stage Cutscene Section","DemoOpeningDokanStageMap1.szs"},
            {"Roulette Minigame Room","RouletteRoomZoneMap1.szs"},
            {"Sprixie House","FairyHouseZoneMap1.szs"},
            {"Sprixie House Lava Backdrop","FairyHouseLavaStageMap1.szs"},
            {"Sprixie House Night Backdrop","FairyHouseNightStageMap1.szs"},
            {"Sprixie House Overworld Backdrop","FairyHouseBlueStageMap1.szs"},
            {"Sprixie House Underground Backdrop","FairyHouseInsideStageMap1.szs"},
            {"\"-1 Rainbow Run - Bonus Room","RainbowRoadBonusZoneMap1.szs"},
            {"\"-1 Rainbow Run - Section 1","RainbowRoadStageMap1.szs"},
            {"\"-1 Rainbow Run - Sky Section","CloudBonusZeldaZoneMap1.szs"},
            {"\"-2 Super Galaxy - Section 1","GalaxyRoadStageMap1.szs"},
            {"\"-2 Super Galaxy Rosalina Cutscene Section","DemoEndRollRosettaStageMap1.szs"},
            {"\"-3 Rolling Ride Run - Bonus Room","WheelMysteryBoxZoneMap1.szs"},
            {"\"-3 Rolling Ride Run - Section 1","WheelCanyonStageMap1.szs"},
            {"\"-4 The Great Goal Pole - Section 1","GoalPoleRunawayStageMap1.szs"},
            {"\"-5 Super Block Land - Section 1","BlockLandStageMap1.szs"},
            {"\"-6 Honeycomb Starway - Section 1","HexScrollStageMap1.szs"},
            {"\"-7 Gargantuan Grotto - Bonus Room","GiantAoCoinZoneMap1.szs"},
            {"\"-7 Gargantuan Grotto - Section 1","GiantUnderGroundStageMap1.szs"},
            {"\"-8 Peepas Fog Bog - Bonus Room","TerenFogGoalZoneMap1.szs"},
            {"\"-8 Peepas Fog Bog - Section 1","TerenFogStageMap1.szs"},
            {"\"-8 Peepas Fog Bog - Section 2","TerenFogBridgeZoneMap1.szs"},
            {"\"-8 Peepas Fog Bog - Section 3","TerenFogMysteryZoneMap1.szs"},
            {"\"-9 Cosmic Cannon Cluster - Section 1","BoxKillerStageMap1.szs"},
            {"\"-Toad Captain Toad Takes a Spin","KinopioBrigadeRotateRoomStageMap1.szs"},
            {"Title Screen","CommonTitleDemoZoneMap1.szs"},
            {"Title Screen Objects Variation 1","TitleDemo00StageMap1.szs"},
            {"Title Screen Objects Variation 2","TitleDemo01StageMap1.szs"},
            {"Title Screen Objects Variation 3","TitleDemo02StageMap1.szs"},
            {"Title Screen Objects Variation 4","TitleDemo03StageMap1.szs"},
            {"Title Screen Objects Variation 5","TitleDemo04StageMap1.szs"},
            {"Title Screen Objects Variation 6","TitleDemo05StageMap1.szs"},
            {"Toad House Blue Sky 1","KinopioHouseBlueZoneMap1.szs"},
            {"Toad House Blue Sky 2","KinopioHouseLv1BlueStageMap1.szs"},
            {"Toad House Blue Sky 2-2","KinopioHouseLv2BlueStageMap1.szs"},
            {"Toad House Blue Sky 3","KinopioHouseLv3BlueStageMap1.szs"},
            {"Toad House Lava Sky 1","KinopioHouseLavaZoneMap1.szs"},
            {"Toad House Lava Sky 2","KinopioHouseLv3LavaStageMap1.szs"},
            {"Toad House Night Sky 1","KinopioHouseLv3NightStageMap1.szs"},
            {"Toad House Night Sky 2","KinopioHouseNightZoneMap1.szs"},
            {"Toad House Underground Sky 1","KinopioHouseInsideZoneMap1.szs"},
            {"Toad House Underground Sky 2","KinopioHouseLv1InsideStageMap1.szs"},
            {"Unused Colour Panel Room","DoremiRoomBZoneMap1.szs"},
            {"World 1 Castle Start Cutscene Section","DemoCourseStartKoopaCastleStageMap1.szs"},
            {"World 1 Map","CourseSelectW1ZoneMap1.szs"},
            {"World 2 Map","CourseSelectW2ZoneMap1.szs"},
            {"World 2 Tank Stage Start Cutscene Section","DemoCourseStartTankStageMap1.szs"},
            {"World 3 Map","CourseSelectW3ZoneMap1.szs"},
            {"World 3 Train Stage Start Cutscene Section","DemoCourseStartTrainStageMap1.szs"},
            {"World 4 Map","CourseSelectW4ZoneMap1.szs"},
            {"World 5 Map","CourseSelectW5ZoneMap1.szs"},
            {"World 6 Map","CourseSelectW6ZoneMap1.szs"},
            {"World 6 Tank Stage Start Cutscene Section","DemoCourseStartTankBombStageMap1.szs"},
            {"World ' Map","CourseSelectW7ZoneMap1.szs"},
            {"World : Map","CourseSelectW8ZoneMap1.szs"},
            {"World : Train Stage Start Cutscene Section","DemoCourseStartTrainEnemyStageMap1.szs"},
            {"World & Map","CourseSelectStageMap1.szs"},
            {"World \"%$ Map","CourseSelectS1ZoneMap1.szs"}
        };
            string Name = Database[LevelName];
            return Name;
        }
    }
}
